name: captaksi_driver_app
description: "Captaksi Sürücü Uygulaması"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # 1. API İstekleri için
  http: ^1.2.1
  
  # 2. Güvenli Token Saklama için
  flutter_secure_storage: ^9.1.1
  
  # 3. Dosya Seçimi (Ehliyet, Profil Resmi vb.)
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  
  # 4. Harita ve Konum Servisleri
  google_maps_flutter: ^2.6.1
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.0.0
  
  # 5. Adres Arama için (Gerekirse)
  uuid: ^4.4.0
  
  # 6. EN ÖNEMLİSİ: Gerçek Zamanlı Bağlantı için
  socket_io_client: ^2.0.3+1
  
  # 7. Firebase Cloud Messaging
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

